In [5]:
import pandas as pd
import numpy as np
df= pd.read_csv("/content/employee_productivity_dataset.csv")

In [6]:
df.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

#Q1. Handle Missing Values (Basic Cleaning)

Fill missing values using the following:

Age → Median

Salary → Mean

Hours_Worked_Per_Week → Median

Performance_Score → Mean

Display the dataset after handling missing values.

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            250 non-null    object
 1   Name                   250 non-null    object
 2   Department             250 non-null    object
 3   Age                    225 non-null    float64
 4   Gender                 250 non-null    object
 5   Work_Mode              250 non-null    object
 6   Join_Date              250 non-null    object
 7   Hours_Worked_Per_Week  200 non-null    float64
 8   Projects_Completed     250 non-null    int64
 9   Performance_Score      200 non-null    float64
 10  Salary                 225 non-null    float64
 11  Location               250 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 23.6+ KB

In [8]:
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
df["Hours_Worked_Per_Week"]=df["Hours_Worked_Per_Week"].fillna(df["Hours_Worked_Per_Week"].median())
df["Performance_Score"]=df["Performance_Score"].fillna(df["Performance_Score"].mean())

In [9]:
print (df)

    Employee_ID         Name Department   Age  Gender Work_Mode   Join_Date  \
0          E001  Amit Sharma         IT  25.0    Male    Remote  15-01-2021
1          E002   Riya Patel         HR  30.0  Female    Hybrid  15-02-2020
2          E003  John Mathew    Finance  29.0    Male    Onsite  10-03-2022
3          E004  Sneha Joshi         IT  28.0  Female    Remote  22-04-2021
4          E005  Arjun Verma  Marketing  35.0    Male    Hybrid  18-05-2020
..          ...          ...        ...   ...     ...       ...         ...
245        E006   Neha Singh         HR  27.0  Female    Remote  01-06-2023
246        E007    Rahul Das    Finance  40.0    Male    Onsite  07-07-2019
247        E008  Pooja Mehta  Marketing  29.0  Female    Hybrid  12-08-2022
248        E009  Sameer Khan         IT  31.0    Male    Remote  30-09-2021
249        E010   Kiran Nair         HR  26.0  Female    Onsite  05-10-2023

     Hours_Worked_Per_Week  Projects_Completed  Performance_Score  \
0                     40.0                   5             4.5000
1                     38.0                   4             4.0000
2                     45.0                   6             4.3125
3                     41.0                   5             4.2000
4                     50.0                   7             4.8000
..                     ...                 ...                ...
245                   36.0                   3             3.9000
246                   48.0                   8             4.7000
247                   42.0                   6             4.3000
248                   41.0                   5             4.1000
249                   37.0                   4             4.3125

           Salary   Location
0    50000.000000       Pune
1    45000.000000     Mumbai
2    60000.000000  Bangalore
3    52000.000000      Delhi
4    50666.666667       Pune
..            ...        ...
245  42000.000000     Mumbai
246  65000.000000      Delhi
247  48000.000000  Bangalore
248  51000.000000       Pune
249  43000.000000     Mumbai

[250 rows x 12 columns]

#Q2. Label Encoding

Convert these columns into numeric values using Label Encoding:

Gender

Department

Show the updated columns

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()

In [12]:
df["Gender"]= le.fit_transform(df["Gender"])
df["Department"]= le.fit_transform(df["Department"])

In [13]:
print(df[["Gender","Department"]])

     Gender  Department
0         1           2
1         0           1
2         1           0
3         0           2
4         1           3
..      ...         ...
245       0           1
246       1           0
247       0           3
248       1           2
249       0           1

[250 rows x 2 columns]

#Q3. One-Hot Encoding

Apply One-Hot Encoding on:

Work_Mode

Location

Display the dataset and check how many new columns are created

In [14]:
df = pd.get_dummies(df, columns=["Work_Mode", "Location"], dtype=int)


print(df)


print("\nTotal number of columns after encoding:", df.shape[1])

    Employee_ID         Name  Department   Age  Gender   Join_Date  \
0          E001  Amit Sharma           2  25.0       1  15-01-2021
1          E002   Riya Patel           1  30.0       0  15-02-2020
2          E003  John Mathew           0  29.0       1  10-03-2022
3          E004  Sneha Joshi           2  28.0       0  22-04-2021
4          E005  Arjun Verma           3  35.0       1  18-05-2020
..          ...          ...         ...   ...     ...         ...
245        E006   Neha Singh           1  27.0       0  01-06-2023
246        E007    Rahul Das           0  40.0       1  07-07-2019
247        E008  Pooja Mehta           3  29.0       0  12-08-2022
248        E009  Sameer Khan           2  31.0       1  30-09-2021
249        E010   Kiran Nair           1  26.0       0  05-10-2023

     Hours_Worked_Per_Week  Projects_Completed  Performance_Score  \
0                     40.0                   5             4.5000
1                     38.0                   4             4.0000
2                     45.0                   6             4.3125
3                     41.0                   5             4.2000
4                     50.0                   7             4.8000
..                     ...                 ...                ...
245                   36.0                   3             3.9000
246                   48.0                   8             4.7000
247                   42.0                   6             4.3000
248                   41.0                   5             4.1000
249                   37.0                   4             4.3125

           Salary  Work_Mode_Hybrid  Work_Mode_Onsite  Work_Mode_Remote  \
0    50000.000000                 0                 0                 1
1    45000.000000                 1                 0                 0
2    60000.000000                 0                 1                 0
3    52000.000000                 0                 0                 1
4    50666.666667                 1                 0                 0
..            ...               ...               ...               ...
245  42000.000000                 0                 0                 1
246  65000.000000                 0                 1                 0
247  48000.000000                 1                 0                 0
248  51000.000000                 0                 0                 1
249  43000.000000                 0                 1                 0

     Location_Bangalore  Location_Delhi  Location_Mumbai  Location_Pune
0                     0               0                0              1
1                     0               0                1              0
2                     1               0                0              0
3                     0               1                0              0
4                     0               0                0              1
..                  ...             ...              ...            ...
245                   0               0                1              0
246                   0               1                0              0
247                   1               0                0              0
248                   0               0                0              1
249                   0               0                1              0

[250 rows x 17 columns]

Total number of columns after encoding: 17

#Q4. Normalization (Min-Max Scaling)

Normalize the following columns:

Salary

Hours_Worked_Per_Week

Use MinMaxScaler and display results.

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler = MinMaxScaler()
df[["Salary", "Hours_Worked_Per_Week"]] = scaler.fit_transform(
    df[["Salary", "Hours_Worked_Per_Week"]])

print(df[["Salary", "Hours_Worked_Per_Week"]])

       Salary  Hours_Worked_Per_Week
0    0.347826               0.285714
1    0.130435               0.142857
2    0.782609               0.642857
3    0.434783               0.357143
4    0.376812               1.000000
..        ...                    ...
245  0.000000               0.000000
246  1.000000               0.857143
247  0.260870               0.428571
248  0.391304               0.357143
249  0.043478               0.071429

[250 rows x 2 columns]

#Q5. Standardization (Scaling)

Apply StandardScaler on:

Age
Projects_Completed

Display the transformed values

In [17]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()


df[["Age", "Projects_Completed"]] = scaler.fit_transform
(
    df[["Age", "Projects_Completed"]]
)


df[["Age", "Projects_Completed"]].head()

,Age,Projects_Completed
0,<bound method TransformerMixin.fit_transform o...,<bound method TransformerMixin.fit_transform o...
1,<bound method TransformerMixin.fit_transform o...,<bound method TransformerMixin.fit_transform o...
2,<bound method TransformerMixin.fit_transform o...,<bound method TransformerMixin.fit_transform o...
3,<bound method TransformerMixin.fit_transform o...,<bound method TransformerMixin.fit_transform o...
4,<bound method TransformerMixin.fit_transform o...,<bound method TransformerMixin.fit_transform o...

 # Q6. Compare Scaling Methods

Apply both:

MinMaxScaler

StandardScaler

On the Salary column.

Show both results side by side.

In [19]:
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()


df["Salary_MinMax"] = minmax_scaler.fit_transform(df[["Salary"]])
df["Salary_Standard"] = standard_scaler.fit_transform(df[["Salary"]])


print(df[["Salary", "Salary_MinMax", "Salary_Standard"]])

       Salary  Salary_MinMax  Salary_Standard
0    0.347826       0.347826    -9.745089e-02
1    0.130435       0.130435    -8.283326e-01
2    0.782609       0.782609     1.364312e+00
3    0.434783       0.434783     1.949018e-01
4    0.376812       0.376812    -3.732632e-16
..        ...            ...              ...
245  0.000000       0.000000    -1.266862e+00
246  1.000000       1.000000     2.095194e+00
247  0.260870       0.260870    -3.898036e-01
248  0.391304       0.391304     4.872545e-02
249  0.043478       0.043478    -1.120685e+00

[250 rows x 3 columns]

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            250 non-null    object
 1   Name                   250 non-null    object
 2   Department             250 non-null    int64
 3   Age                    250 non-null    object
 4   Gender                 250 non-null    int64
 5   Join_Date              250 non-null    object
 6   Hours_Worked_Per_Week  250 non-null    float64
 7   Projects_Completed     250 non-null    object
 8   Performance_Score      250 non-null    float64
 9   Salary                 250 non-null    float64
 10  Work_Mode_Hybrid       250 non-null    category
 11  Work_Mode_Onsite       250 non-null    int64
 12  Work_Mode_Remote       250 non-null    int64
 13  Location_Bangalore     250 non-null    int64
 14  Location_Delhi         250 non-null    int64
 15  Location_Mumbai        250 non-null    int64
 16  Location_Pune          250 non-null    int64
 17  Salary_MinMax          250 non-null    float64
 18  Salary_Standard        250 non-null    float64
dtypes: category(1), float64(5), int64(8), object(5)
memory usage: 35.7+ KB

In [31]:
df["Work_Mode_Hybrid"] = df["Work_Mode_Hybrid"].astype("category")

#Q7. Build Preprocessing Pipeline

Create a pipeline that:

Applies encoding to categorical columns

Applies scaling to numerical columns

Use:

ColumnTransformer

Pipeline

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Categorical and Numerical columns
cat_cols = ['Work_Mode_Hybrid']
num_cols = ['Hours_Worked_Per_Week', 'Salary_Standard']

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), cat_cols),
        ('num', StandardScaler(), num_cols)
    ]
)

# Pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

# Apply pipeline
result = pipeline.fit_transform(df)

print(result)

[[ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]]

#Q8. Apply Pipeline

Apply the pipeline on the dataset.

Display:

Transformed dataset

Shape of final dataset

In [29]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [36]:
# Categorical and Numerical columns
cat_cols = ['Work_Mode_Hybrid']
num_cols = [ 'Hours_Worked_Per_Week', 'Salary_Standard']

# Column Transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), cat_cols),
        ('num', StandardScaler(), num_cols)
    ]
)

# Pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

# Apply Pipeline
transformed_data = pipeline.fit_transform(df)

# Display transformed dataset
print(transformed_data)

# Shape of final dataset
print("Shape:", transformed_data.shape)



transformed_df = pd.DataFrame(transformed_data)

transformed_df.head()

print("Shape:", transformed_df.shape)

[[ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]
 [ 1.00000000e+00  0.00000000e+00 -4.11220496e-01 -9.74508910e-02]
 [ 0.00000000e+00  1.00000000e+00 -8.68132159e-01 -8.28332574e-01]
 [ 1.00000000e+00  0.00000000e+00  7.31058660e-01  1.36431247e+00]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  1.94901782e-01]
 [ 0.00000000e+00  1.00000000e+00  1.87333782e+00 -2.95547558e-16]
 [ 1.00000000e+00  0.00000000e+00 -1.32504382e+00 -1.26686158e+00]
 [ 1.00000000e+00  0.00000000e+00  1.41642615e+00  2.09519416e+00]
 [ 0.00000000e+00  1.00000000e+00  4.56911662e-02 -3.89803564e-01]
 [ 1.00000000e+00  0.00000000e+00 -1.82764665e-01  4.87254455e-02]
 [ 1.00000000e+00  0.00000000e+00 -1.09658799e+00 -1.12068525e+00]]
Shape: (250, 4)
Shape: (250, 4)

# Q9. Why is scaling important in Python?

Scaling is an important data preprocessing step in Python, especially when working with Machine Learning.

Scaling means converting numerical features to a similar range or scale, so that one feature does not unfairly dominate another.

Why is scaling important?
#Prevents large-valued features from dominating
A feature with values in thousands shouldn't automatically have more influence than one with values between 0 and 100.

#Improves distance-based algorithms
Scaling is particularly important for:
K-Nearest Neighbors (KNN)
K-Means Clustering
Support Vector Machines (SVM)

#Helps optimization converge faster
Algorithms such as Linear Regression, Logistic Regression, and Neural Networks can benefit from appropriately scaled features.

#Makes features comparable
Different units such as age, income, weight, and treatment cost can be brought to a common scale.

#Q10. Why do we convert categorical data into numerical form?

#We convert categorical data into numerical form because most machine learning algorithms work with numbers, not text labels.

#1. Label Encoding

For categories with an order, we can assign numbers.

#2. One-Hot Encoding

For categories without an order, one-hot encoding is usually safer.